
# List of textures which will be denied upload.
#
# Valid values: ["skin", "cape", "elytra"]
# texture_type_denylist = ["cape"]

# The secret key used to sign the session data.
#
# It's important to change this from the default. Use the following command to create a
# new secret key.
#
# $ openssl rand -base64 24
#
# secret_key = "dev"

# The url to the database. Supports sqlite and postgresql.
#
# database_url = "postgresql://user:pass@host:5432/dbname"
# database_url = "sqlite:///./valhalla.db"

# The S3 bucket to store uploaded textures in.
#
# textures_bucket = ""

# The base path to where uploaded textures are stored.
#
# For S3, it behaves as a key prefix
#
# textures_path = "textures"

# The url to where the textures will be accessed on the client.
#
# For s3, will be https://{bucket-name}.s3.amazonaws.com/ or your configured domain alias.
#
# If empty, will assume same origin.
#
# textures_url = "https://foobar.s3.amazonaws.com"

# xbox_live_client_id = ""

# xbox_live_client_secret = ""

# xbox_live_server_metadata_url = "https://login.live.com/.well-known/openid-configuration"

# xbox_live_client_kwargs = {scope = "XboxLive.signin offline_access"}

# aws_endpoint_url = ""

# aws_access_key_id = ""

# aws_secret_access_key = ""
