"""v1

Revision ID: 6ca6cdcf1416
Revises: 0447a53e7d20
Create Date: 2022-11-05 14:24:57.344299

"""

from datetime import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ca6cdcf1416"
down_revision = "0447a53e7d20"
branch_labels = None
depends_on = None


UNIX_ERA = datetime(1970, 1, 1)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secret_sanity")
    with op.batch_alter_table("textures") as t:
        t.add_column(  # type: ignore
            sa.Column(
                "start_time",
                sa.DateTime(),
                nullable=False,
                server_default=UNIX_ERA.isoformat(),
            )
        )
        t.add_column(sa.Column("end_time", sa.DateTime(), nullable=True))  # type: ignore
        t.alter_column("upload_id", existing_type=sa.INTEGER(), nullable=False)  # type: ignore
    op.drop_column("users", "address")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "address", sa.VARCHAR(length=50), nullable=False, server_default="127.0.0.1"
        ),
    )
    with op.batch_alter_table("textures") as t:
        t.alter_column("upload_id", existing_type=sa.INTEGER(), nullable=True)  # type: ignore
        t.drop_column("end_time")  # type: ignore
        t.drop_column("start_time")  # type: ignore
    op.create_table(
        "secret_sanity",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("secret", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
