"""secret sanity

Revision ID: 052f0fb7b5ec
Revises: 84c77598d2be
Create Date: 2019-10-17 20:04:17.228622

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '052f0fb7b5ec'
down_revision = '84c77598d2be'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_sanity',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('secret', sqlalchemy_utils.types.password.PasswordType(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_sanity')
    # ### end Alembic commands ###
