"""v1

Revision ID: 84c77598d2be
Revises: 
Create Date: 2019-10-13 01:11:12.154165

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '84c77598d2be'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('address', sqlalchemy_utils.types.ip_address.IPAddressType(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('uuid'))
    op.create_table('uploads',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hash', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('upload_time', sa.DateTime(), server_default='now()', nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('hash'))
    op.create_table('textures',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('upload_id', sa.Integer(), nullable=True),
                    sa.Column('tex_type', sa.String(), nullable=False),
                    sa.Column('meta', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('textures')
    op.drop_table('uploads')
    op.drop_table('users')
    # ### end Alembic commands ###
