name: ruff

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Lint and format with ruff
      run: |
        uv run ruff check
        uv run ruff format --check
